site_name: NEWDB API Docs
site_description: Документация по REST API NEWDB и метаданные для AI-агентов
site_url: https://newdb.net/docs
use_directory_urls: true

theme:
  name: material
  language: ru
  features:
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

nav:
  - Главная: index.md
  - Физические лица:
      - Обзор: fiz/README.md
      - Проверка ФЛ (ФССП): fiz/01-fssp_person.md
      - Проверка паспорта и ИНН через ФНС: fiz/02-passport_fns.md
      - Проверка паспорта РФ на действительность: fiz/03-passport_mvd.md
      - Комплексная проверка по паспорту: fiz/04-complex_by_passport.md
      - Проверка на банкротство (Федресурс): fiz/05-fedresurs_bankrot.md
      - Залоги : fiz/06-pledge_person.md

  - Юридические лица:
      - Обзор: legal/index.md
  - Имущество:
      - Обзор: property/index.md

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - toc:
      permalink: true

extra:
  api_base_url: https://api.newdb.net/v2
  base_path: /docs/
